[phases.setup]
nixPkgs = [
  "python313",
  "libx11",
  "libxcomposite",
  "libxcursor",
  "libxdamage",
  "libxext",
  "libxfixes",
  "libxi",
  "libxrandr",
  "libxrender",
  "libxinerama",
  "atk",
  "at-spi2-atk",
  "dbus"
]

[start]
cmd = "python server.py"
